INSERT INTO UNIVERSITYSTAFFS VALUES (100,'suKK90_Sark','faculty');
INSERT INTO UNIVERSITYSTAFFS VALUES (200,'supA56_ark','admission committee');
INSERT INTO UNIVERSITYSTAFFS VALUES (300,'sup9ft_tSark','head');
INSERT INTO UNIVERSITYSTAFFS VALUES (400,'sup9fs_Sark','coordinator');
INSERT INTO UNIVERSITYSTAFFS VALUES (500,'sup99@Sark','admission committee');